# Generated by Django 3.2.12 on 2024-06-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20240604_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.TimeField(auto_now=True),
        ),
    ]
