# Generated by Django 3.2.12 on 2024-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
