# Generated by Django 3.2.12 on 2024-06-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Safaricom', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
    ]
